/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RocketModel */

#ifndef _Included_RocketModel
#define _Included_RocketModel
#ifdef __cplusplus
extern "C" {
#endif
#undef RocketModel_EARTH_RADIUS
#define RocketModel_EARTH_RADIUS 6371000.0
#undef RocketModel_GRAVITATIONAL_CONSTANT
#define RocketModel_GRAVITATIONAL_CONSTANT 6.6743E-11
#undef RocketModel_EARTH_MASS
#define RocketModel_EARTH_MASS 5.972E24
#undef RocketModel_MAX_ANGLE_CHANGE_RATE
#define RocketModel_MAX_ANGLE_CHANGE_RATE 10.0
/*
 * Class:     RocketModel
 * Method:    nativeUpdateRocketState
 * Signature: (DDDDDDDDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_RocketModel_nativeUpdateRocketState
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     RocketModel
 * Method:    nativeCalculateOrbitAngle
 * Signature: (DDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_RocketModel_nativeCalculateOrbitAngle
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
